### ISSUE TITLE
training data.

### ISSUE THREAD

**Issue by JunZhang0629** [leventt/surat#1]
Hi, surat.  Thanks for recreating the code available for the community. I am working on reproducing your results as part of research work. You did not provide trainable dataset and eval code. How would i create/acquire precalculatedAutoCorrelations.npy files, if i want to do train/inference on any arbitrary data.

**Comment by leventt** [comment]
Hi! Unfortunately the data I used were mostly from demos and example files I found part of evaluating some other commercial solutions. Those data wouldn't be mine to provide. I am working on generating my own data which I would provide when ready. I am not working on this actively until another month or two. precalculated auto correlations are auto generated when you specify your audio source to train with on the first run. Autocorrelation implementation I used wasn't fast enough so first time the audio is loaded, it will precalculate and save. You would need matching animation to your audio if you want to create your data. The way code is setup now, it would expect 51 morph targets. You can change that count in code if you have another rig. I am planning to write up some documentation along with the data when I am ready to provide that. Cheers!

**Comment by leventt** [comment]
I am hopefully going to put this online soon:
https://vimeo.com/396595682

It won't be morph targets unfortunately it looks like but it may be more faithful to the original publication this way for other people to validate.

I might try to salvage morph targets with FACS later on.

**Comment by leventt** [comment]
Hi I would be willing to share my rough data so you can experiment as I do. Let me know what you are planning to use it for and I can ask the voice actor for his permission to share the data with you.

Also check out this post for the overall project called yakamoz.io
https://medium.com/@leventtasel/understanding-the-face-8d2989fe93db

**Comment by bigpo** [comment]
> Hi I would be willing to share my rough data so you can experiment as I do. Let me know what you are planning to use it for and I can ask the voice actor for his permission to share the data with you.
> 
> Also check out this post for the overall project called yakamoz.io
> https://medium.com/@leventtasel/understanding-the-face-8d2989fe93db

hi, @leventt , thanks for your nice work! i really appreciate if you can share your dataset so that i can reproduce this work , or let me know how to create the dataset , thanks!

**Comment by lvZic** [comment]
> > Hi I would be willing to share my rough data so you can experiment as I do. Let me know what you are planning to use it for and I can ask the voice actor for his permission to share the data with you.
> > Also check out this post for the overall project called yakamoz.io
> > https://medium.com/@leventtasel/understanding-the-face-8d2989fe93db
> 
> hi, @leventt , thanks for your nice work! i really appreciate if you can share your dataset so that i can reproduce this work , or let me know how to create the dataset , thanks!

你好 想问下 你后来有找到可以用来训练的数据吗

**Comment by bigpo** [comment]
> > > Hi I would be willing to share my rough data so you can experiment as I do. Let me know what you are planning to use it for and I can ask the voice actor for his permission to share the data with you.
> > > Also check out this post for the overall project called yakamoz.io
> > > https://medium.com/@leventtasel/understanding-the-face-8d2989fe93db
> > 
> > 
> > hi, @leventt , thanks for your nice work! i really appreciate if you can share your dataset so that i can reproduce this work , or let me know how to create the dataset , thanks!
> 
> 你好 想问下 你后来有找到可以用来训练的数据吗

sorry, i didn't find useful data

**Comment by leventt** [comment]
nvidia released their work as a tool where I believe they should have kept the work from original publication. you can use that and generate data with it too:
https://www.nvidia.com/en-us/omniverse/apps/audio2face/

**Comment by NedaZand** [comment]
Hi @leventt 
I have worked with Nvidia Audio2Face but I dont know how to prepare the dataset
Would you please share your training dataset then I can realize how to prepare my own dataset
Thanks in advance

**Comment by leventt** [comment]
I have a custom dataset prepared after recording an actor and I am not going to share it. I am not going to try audio2face to make an example dataset either.
