### ISSUE TITLE
How to install and run?

### ISSUE THREAD

**Issue by ghost** [leventt/surat#2]
It seems this project code is incomplete

**Comment by leventt** [comment]
Things are in flux and I make a few changes a day, as I train this, with a new data-set to put a demo on [https://yakamoz.io](https://yakamoz.io)

[https://beta.yakamoz.io](https://beta.yakamoz.io) is where it is at for now.

Here is a longer write-up for the overall project:
https://medium.com/@leventtasel/understanding-the-face-8d2989fe93db

Let me know what you need and we can install it and run it together perhaps.

**Comment by woobin3069** [comment]
@leventt  Hello, I also tried to install and run it, but I can't run it without samSour data.
I visited yakamoz.io and your medium to get the dataset, but both of them are shut down.
Is there any way I can run this code?

**Comment by leventt** [comment]
I can't provide the data unfortunately and without it, you would have to acquire some before running it. NVIDIA released some version of this as a product in their tool called Omniverse iirc. You may want to check that one if you just want to run something that implements the paper this references.

**Comment by woobin3069** [comment]
Wow, Thank you for a really quick answer. I'll check Omniverse IIRC. Sorry if I was too rude. Once again, thank you.

**Comment by leventt** [comment]
no worries. here is a link:
https://www.nvidia.com/en-us/omniverse/apps/audio2face/
