### ISSUE TITLE
Outputting Morph targets with FACS / ARkit

### ISSUE THREAD

**Issue by mbdash** [leventt/surat#3]
Hi @leventt, thank you for this repo.

I am currently stuck when it comes to voca as it requires a 3D mesh registered with FLAME, 
and I don't know how to do that other then passing an image to RingNet...
Also it is outputting vtx data instead of morph targets which is not very engine / game friendly.

**Having a software that can convert audio to data compatible with the ARkit sdk might be of a great benefit to the indies out there...**
https://developer.apple.com/documentation/arkit/arfaceanchor/blendshapelocation

That been said,

**What kind of data would you require to make this repo output data for morph targets with FACS / ARkit compatible?**
How many minutes? 
How many actors?
Maybe there is a way to build a public dataset with volunteers or paid voice actors.

How much GPU power do you currently have at your disposal? 
At the moment, my GPU power is limited to a single 2080ti.
It is currently running experiments and training models for another GitHub project, to thank it's community for their help and support it's great project. 
**I would gladly contribute some GPU power to train models and run experiments to help this repo or a fork dedicated to morph targets with FACS / ARkit compatible.**

**Comment by leventt** [comment]
Hi @mbdash 

I tested this model with different adjustments that can bee seen in commits with both FACS data and per vertex data. I am not convinced that my code is matching the original publication since it was suggested that 3 to 5 minutes of data should have been enough with a single actor. However I got mixed results.
I have a 1080ti which was enough for my tests and thanks for the offer. I believe more data would be better and any help would be appreciated.

**Comment by mbdash** [comment]
Alright, 
before I start poking around to find ppl with an apple device with TrueDepth Cameras;
do you have any guidelines, do's and don't, preferred data length, etc for the output data?

**Comment by leventt** [comment]
Here are a couple datasets that you can reference:
https://zenodo.org/record/1188976#.XrC7a5NKjOR
https://catalog.ldc.upenn.edu/LDC93S1

I believe more data would be better however it is important to have some variation for emotional performance and visemes.
