### ISSUE TITLE
A question about the `self.inputValues` in surat.py

### ISSUE THREAD

**Issue by MysteryOfLove** [leventt/surat#6]
Hi, Surat @leventt . Thank you share the code!

I have a question about the `self.inputValues` in surat.py

link: https://github.com/leventt/surat/blob/master/surat.py#L70-L86
```
                self.inputValues = torch.cat(
                    (
                        self.inputValues,
                        torch.cat(
                            (
                                self.LPC(
                                    torch.roll(self.waveform[0:1, :], audioIdxRoll, dims=0)[:, :audioFrameLen]
                                ).view(1, 1, 64, 32),
                                self.LPC(
                                    torch.roll(self.waveform[0:1, :], audioIdxRollPair, dims=0)[:, :audioFrameLen]
                                ).view(1, 1, 64, 32)
                            ),
                            dim=0,
                        ).view(2, 1, 64, 32)
                    ), dim=0
                ).view(-1, 1, 64, 32)
            self.inputValues = self.inputValues.view(-1, 2, 1, 64, 32)
```

What does this `audioIdxRoll` mean?
`torch.roll()` will shift the elemens  of the `self.waveform` tensor, but if you setting dims=0, `audioIdxRoll` does not work, because the shape of `self.waveform[0:1, :]` is [1, audio_samples].

I am looking forward to hearing from you soon, Thanks!

**Comment by leventt** [comment]
This was for data augmentation. Paper mentions random shifts from 0 to 16 ms iirc. That is implemented as a slice from the rolled tensor.

**Comment by leventt** [comment]
also check this out:
https://github.com/leventt/leventt.github.io/tree/master/avaz%2Ftraining

this is a minimal implementation of the same thing and I don't think I do the data augmentation here, so it can be good to compare.

there is a demo for this that works in some browsers:
leventtasel.com/avaz/avaz

**Comment by MysteryOfLove** [comment]
> This was for data augmentation. Paper mentions random shifts from 0 to 16 ms iirc. That is implemented as a slice from the rolled tensor.

I see. Thank you for your answer!

**Comment by MysteryOfLove** [comment]
> also check this out: https://github.com/leventt/leventt.github.io/tree/master/avaz%2Ftraining
> 
> this is a minimal implementation of the same thing and I don't think I do the data augmentation here, so it can be good to compare.
> 
> there is a demo for this that works in some browsers: leventtasel.com/avaz/avaz

OK. Thanks for sharing!
